---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

## EO BMF

EXEMPT ORGANIZATIONS BUSINESS MASTER FILE EXTRACT

```{r}
regions <- c("1", "2", "3", "4", "_xx", "_pr")
eo <- map_dfr(regions,
              ~ read_csv(str_glue("https://www.irs.gov/pub/irs-soi/eo{.x}.csv"),
                         col_types = "cccccccccccccccccccccccnnncc")) %>%
  distinct()
```

```{r}
eo %>%
  mutate(across(where(is.character), as.factor)) %>%
  summary()
```

```{r}
eo %>%
  group_by(NTEE_CD) %>%
  summarise(across(where(is.numeric), sum, na.rm = TRUE)) %>%
  mutate(across(where(is.numeric),
                ~ paste0(format(round(.x/1e6), big.mark = ",",
                                scientific = FALSE), "M"))) %>%
  arrange(desc(ASSET_AMT)) %>%
  mutate(NTEE_CD = str_sub(NTEE_CD, 1, 3)) %>%
  left_join(ntee_map %>% mutate(name = str_sub(name, 1, 3)),
            by = c("NTEE_CD" = "name")) %>%
  select(desc, ends_with("_AMT")) %>%
  head(1000) %>%
  DT::datatable()
```

```{r}
ntee_json <- jsonlite::fromJSON("https://raw.githubusercontent.com/dhenderson/ntee/master/ntee.json")
ntee_map <- map_dfr(names(ntee_json), ~ tibble(name = .x, desc = ntee_json[[.x]]$title))

```


